# -------------------------------
# API Documentation & Testing
# -------------------------------

# 1. User Authentication

## Register a new user
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "luqman",
  "email": "luq1@gmail.com",
  "password": "password123",
  "role": "user"
}

### 

## Login user and get JWT token
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "luq@gmail.com",
  "password": "password123"
}

# Response:
# {
#   "message": "Login successful",
#   "token": "your_jwt_token"
# }

### 

# 2. Poll Management (Admin)

## Create a new poll (Admin only)
POST http://localhost:5000/api/polls/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NWQ3ZmRjMzg0MmI0ODQ5NmY5MzkzZSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczNDE4MDkwNiwiZXhwIjoxNzQxOTU2OTA2fQ.9hb-74NrJvhsuh-V94bnxhvhvr_TFM08OrqGVNYJvbU


{
  "title": "poll pooll poll?",
  "question": "What is your favorite color?",
  "options": ["Red", "Blue", "Green", "Yellow"]
}


# Response:
# {
#   "message": "Poll created successfully",
#   "pollId": "unique_poll_id"
# }

### 

## Publish a poll (Admin only)
PUT http://localhost:5000/api/polls/publish/675d704d07a315fa5e9304ea
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NWVhMTI3Y2U5MWY4ZTAxMWM0YjllYSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczNDI2ODY1MCwiZXhwIjoxNzQyMDQ0NjUwfQ.sOQhbd8KCUdiB_F_QGJTLAR0-2NsQuDT-O2u5n6y6HI

# Response:
# {
#   "message": "Poll published successfully"
# }

### 

## Get all polls (Admin or User)
GET http://localhost:5000/api/polls
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NWZhOWNkOGRkNzhhNjMyMzNhNzIxZSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczNDMyMzc3MSwiZXhwIjoxNzQyMDk5NzcxfQ.gKUnW57yXo6_GT8gmD60GoKjMWnkfUISYE_8t21Y7bo
# Response:
# [
#   {
#     "pollId": "unique_poll_id_1",
#     "question": "What is your favorite color?",
#     "options": ["Red", "Blue", "Green", "Yellow"],
#     "createdAt": "2024-12-01T12:00:00Z"
#   },
#   {
#     "pollId": "unique_poll_id_2",
#     "question": "Which programming language do you prefer?",
#     "options": ["JavaScript", "Python", "Java", "C#"],
#     "createdAt": "2024-12-02T12:00:00Z"
#   }
# ]


### 





## Register a new user (test for users who cast vote)
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "luqmanvoter",
  "email": "luqvoter@gmail.com",
  "password": "password123",
  "role": "user"
}

### 

## Login user and get JWT token
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "luqvoter@gmail.com",
  "password": "password123"
}

###
# 3. Voting (User)

## Cast a vote on a poll
POST http://localhost:5000/api/votes/cast
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NWQ3MWZmMDdhMzE1ZmE1ZTkzMDRmMCIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzM0MTc3Mjg3LCJleHAiOjE3NDE5NTMyODd9.K-Pv78qJS1wBbU-Un9oSGWXOxLLoh-tn6e3bnUaIY4I

{
  "pollId": "675d704d07a315fa5e9304ea",
  "option": "Blue"
}

# Response:
# {
#   "message": "Vote cast successfully"
# }

# Error Response (If user has already voted):
# {
#   "message": "You have already voted on this poll"
# }

### 

# -------------------------------
# End of API Documentation & Testing
# -------------------------------
